org: '1259665364'
app: autopony
stage: dev
component: flask
name: flask-YlewOMsdP
inputs:
  src:
    hook: pip3 install -r requirements.txt -t ./
    dist: ./
    exclude:
      - .env
  region: ap-hongkong
  runtime: Python3.6
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
    serviceTimeout: 60
    autoCreateDns: false
  isAutoCiDeploy: false
  functionConf:
    eip: true
    timeout: 21
    memorySize: 128
